layout_spectrum: 1
typography_spectrum: 0.06661046
color:
  lightness: 0.7234401
  brandStrength: 0.5438449
  saturation: 0.7344013
  rhythmicContrast: 0.8659359
  brandColors:
    - '#CFCFBD'
    - '#0C0D0C'
    - '#CF291D'
    - '#E94C41'
    - '#393930'
name: Discover Symbols
